create table player_gameweeks (
    id SERIAL UNIQUE,
    player_id int NOT null,
    player_name varchar(255),
    assists int,
    bonus int,
    bps int,
    clean_sheets int,
    creativity int,
    element int,
    fixture int,
    goals_conceded int,
    goals_scored int,
    ict_index int,
    influence int,
    kickoff_time timestamp,
    minutes int,
    opponent_team int,
    own_goals int,
    penalties_missed int,
    penalties_saved int,
    red_cards int,
    round int,
    saves int,
    selected int,
    team_a_score int,
    team_h_score int,
    threat int,
    total_points int,
    transfers_balance int,
    transfers_in int,
    transfers_out int,
    value int,
    was_home bool,
    yellow_cards int,
    PRIMARY KEY (id),
    FOREIGN KEY (player_id) REFERENCES players(player_id) 
)